version: '2'
services:
  qacert-app:
    image: stgconsulting/qacert:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://qacert-postgresql:5432/QaCert
      - JHIPSTER_SLEEP=10 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  qacert-postgresql:
    extends:
      file: postgresql.yml
      service: qacert-postgresql
